version: '3.8'

services:
  api:
    image: node:latest
    container_name: wankuldex-api-node
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "54112:5000"
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wankuldex.rule=Host(`wankuldex-api.timeuh.fr`)"
      - "traefik.http.routers.wankuldex.entrypoints=websecure"
      - "traefik.http.routers.wankuldex.certresolver=myresolver"
    command: node api/index.ts
    tty: true


  database:
    image: postgres:latest
    container_name: wankuldex-api-database
    restart: always
    ports:
      - "54113:5432"
    networks:
      - traefik_web

  adminer:
    image: adminer:latest
    container_name: wankuldex-api-adminer
    restart: always
    ports:
      - "54114:8080"
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
  default:
    driver: bridge