services:
  api:
    image: node:latest
    container_name: wankuldex-api-node-test
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "54112:5000"
    networks:
      - dokploy-network
    command: npm run pm2
    tty: true
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: wankuldex-api-database-test
    restart: unless-stopped
    networks:
      - dokploy-network
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: wankuldex-api-adminer-test
    restart: unless-stopped
    ports:
      - "54114:8080"
    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true
