version: '3.8'

services:
  api:
    image: node:latest
    container_name: wankuldex-api-node
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "54112:5000"
    networks:
      - traefik_web
    command: npm run pm2
    tty: true
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wankuldex-api.rule=Host(`wankuldex-api.timeuh.fr`)"
      - "traefik.http.routers.wankuldex-api.entrypoints=websecure"
      - "traefik.http.routers.wankuldex-api.tls.certresolver=myresolver"
      - "traefik.http.services.api-service.loadbalancer.server.port=5000"

  database:
    image: postgres:latest
    container_name: wankuldex-api-database
    restart: always
    ports:
      - "54113:5432"
    networks:
      - traefik_web
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: wankuldex-api-adminer
    restart: always
    ports:
      - "54114:8080"
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-wankuldex-api.rule=Host(`admin.wankuldex-api.timeuh.fr`)"
      - "traefik.http.routers.admin-wankuldex-api.entrypoints=websecure"
      - "traefik.http.routers.admin-wankuldex-api.tls.certresolver=myresolver"


networks:
  traefik_web:
    external: true
  default:
    driver: bridge
